# Generated by Django 5.2 on 2025-05-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_venta_productos_carrito_detalle_delete_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta_productos',
            name='webpay_payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta_productos',
            name='webpay_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venta_productos',
            name='estado_venta',
            field=models.CharField(choices=[('carrito', 'Carrito'), ('pagado', 'Pagado')], default='carrito', max_length=200),
        ),
    ]
